#define CHORDAL_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 5000
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define RETRO_TAPPING
#define TAPPING_TERM 200
